### ISSUE TITLE
ADVENT

### ISSUE THREAD

**Issue by det-tu** [jxhuang0508/HCL#1]
I feel like the implementation applies ADVENT as a additional content while training in target domain, which was not mentioned in the paper? Can you provide more details about the implementation? Thank you :)

**Comment by jxhuang0508** [comment]
Hi,

ADVENT is used as the codebase only. The target data is not used when training the source model, as shown in https://github.com/jxhuang0508/HCL/blob/42f8ebbad03c7694d60acb4e18c6c35f4a644be0/hcl/domain_adaptation/train_UDA.py#L127.

**Comment by yihong-97** [comment]
> Hi,
> 
> ADVENT is used as the codebase only. The target data is not used when training the source model, as shown in
> 
> https://github.com/jxhuang0508/HCL/blob/42f8ebbad03c7694d60acb4e18c6c35f4a644be0/hcl/domain_adaptation/train_UDA.py#L127
> 
> .

I confused that the training of the source model seems to use the ADVENT'code, as shown in
> https://github.com/jxhuang0508/HCL/blob/3f01a13702d2601cceb96cd3e01c8ffa0b2c5597/hcl/scripts/train.py#L17

**Comment by jxhuang0508** [comment]
Hi, this bug has been fixed by replacing 'advent' dir with 'hcl' dir:
https://github.com/jxhuang0508/HCL/blob/db54aacd5acdc71cbb014d88b84674b4e3a89f66/hcl/scripts/train.py#L18
